package(default_visibility = ["//tensorflow_federated:__subpackages__"])

licenses(["notice"])

#package_group(
#    name = "research",
#    packages = ["//tensorflow_federated/python/research/..."],
#)

py_library(
    name = "research",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        "//tensorflow_federated/python/research/gans",
        "//tensorflow_federated/python/research/utils",
    ],
)
